option(VSH_BUILD_TESTS "Build tests" OFF)
message(STATUS "VSH_BUILD_TESTS=${VSH_BUILD_TESTS}")

option(VSH_BUILD_DRIVER "Build driver" ON)
message(STATUS "VSH_BUILD_DRIVER=${VSH_BUILD_DRIVER}")

option(VSH_BUILD_BENCHMARKS "Build benchmarks" OFF)
message(STATUS "VSH_BUILD_BENCHMARKS=${VSH_BUILD_BENCHMARKS}")
